project:
  type: website
  resources:
    - "images/"
  preview:
    port: 8050

website:
  title: "Cex - Comprehensively EXtended C Language"
  #repo-url: "https://github.com/alexveden/cex_docs"
  repo-actions:
    - source
    - edit 
    - issue
  navbar:
    tools:
      - icon: github
        href: https://github.com/alexveden/cex
  sidebar:
    style: "docked"
    contents: auto

  search: 
    location: sidebar
    type: textbox

format:
  html:
    theme: darkly
    css: _include/styles.css
    toc: true
    toc-location: body
    highlight-style: github
    syntax-definitions:
      - _include/cex_syntax.xml 

filters:
- _include/callouts.lua
