project:
  type: website
  resources:
    - "images/"
  preview:
    port: 8050

website:
  title: "Cex - Comprehensively EXtended C Language"
  #repo-url: "https://github.com/alexveden/cex_docs"
  repo-actions:
    - source
    - edit 
    - issue
  navbar:
    tools:
      - icon: github
        href: https://github.com/alexveden/cex
  sidebar:
    style: "docked"
    contents:
      - section: "Introduction"
        contents:
          - getting_started.md
          - install.md
          - features.md
          - examples.md
      - section: "CEX language"
        contents:
          - cex_language/basics.md
          - cex_language/errors.md
          - cex_language/memory.md

  search: 
    location: sidebar
    type: textbox

format:
  html:
    theme: darkly
    css: _include/styles.css
    toc: true
    toc-location: body
    highlight-style: github
    html-math-method: plain
    syntax-definitions:
      - _include/cex_syntax.xml 

filters:
- _include/callouts.lua
